version: '3'
services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./src:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
      
  db:
    image: mysql:8.2
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./src/db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dento
      MYSQL_DATABSE: dento_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"


